user:
  username: puppetop
  pass: puppet
  nome: Panzi
  cognome: Sbonzi
app:
  main:
    package: com.spritzleaf.puppet.mvc
spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    suffix: .html
    content-type: text/html
    enable: true
    encoding: UTF-8
